const $=s=>document.querySelector(s), groups=['Chest','Back','Shoulders','Biceps','Triceps','Forearms','Quads','Hamstrings','Glutes','Calves','Core'];
const colors=['#249cff','#66c6ff','#657fff','#39d6c0','#a190ff','#40b8de','#3572c8','#72a6ff','#45a6a6','#babaff','#7189ba'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:1});
let report,weights=[],client,user,localMode=true;
function status(t){$('#status').textContent=t}
function chart(rows,key,line=false,average=false){
 if(!rows.length)return '<p class="muted">No entries in this range.</p>';
 const vals=rows.map(r=>Number(r[key]||0)),max=Math.max(...vals,1)*1.1,w=600,h=185,n=rows.length,step=530/Math.max(n,1);
 let svg='<svg viewBox="0 0 600 235" role="img" aria-label="'+esc(key)+' over time">';
 for(let i=0;i<4;i++){let y=20+i*h/3;svg+=`<line x1="50" x2="590" y1="${y}" y2="${y}" stroke="#253248" stroke-dasharray="3 5"/><text x="3" y="${y+4}">${fmt(max*(1-i/3))}</text>`}
 const x=i=>50+step*(i+.5),y=v=>20+h*(1-v/max);
 if(line){svg+=`<polyline fill="none" stroke="#249cff" stroke-width="3" points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`; vals.forEach((v,i)=>svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#67c6ff"><title>${esc(rows[i].date||rows[i].week)}: ${fmt(v)}</title></circle>`)}
 else vals.forEach((v,i)=>svg+=`<rect x="${x(i)-step*.33}" y="${y(v)}" width="${Math.max(1,step*.66)}" height="${h+20-y(v)}" rx="3" fill="#249cff"><title>${esc(rows[i].week||rows[i].date)}: ${fmt(v)}</title></rect>`);
 if(average){const av=rows.map((r,i)=>{let window=rows.slice(0,i+1).filter(t=>(new Date(r.date)-new Date(t.date))/86400000<=6);return window.reduce((a,t)=>a+t[key],0)/window.length});svg+=`<polyline fill="none" stroke="#61e3bc" stroke-width="2" points="${av.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`}
 const indexes=[...new Set([0,Math.floor(n/2),n-1])];indexes.forEach(i=>svg+=`<text x="${x(i)}" y="228" text-anchor="middle">${esc((rows[i].week||rows[i].date).slice(5))}</text>`);return svg+'</svg>';
}
const working=s=>!['warmup','warm-up'].includes(s.type.toLowerCase());
function active(){return report.sets.filter(s=>working(s)&&s.date>=$('#from').value&&s.date<=$('#to').value)}
function load(r){if(!r||r.schema_version!==1||!Array.isArray(r.sets)||!r.sets.length||!Array.isArray(r.exercises))throw Error('Invalid report: use analyzer/analyze.py output');report=r;$('#dashboard').hidden=false;$('#from').value=r.range.start;$('#to').value=r.range.end;$('#exercise').innerHTML=r.exercises.map(e=>`<option>${esc(e.name)}</option>`).join('');$('#quality').textContent=`${r.quality.blank_rows_skipped} empty rows skipped · ${r.quality.duplicate_sets_skipped} overlapping sets deduplicated · RPE coverage ${r.quality.rpe_coverage}% · Unmapped: ${r.quality.unmapped_exercises.join(', ')||'none'}`;$('#methodology').innerHTML=r.methodology.map(t=>`<li>${esc(t)}</li>`).join('');render();renderWeights();}
function render(){if(!report)return;let sets=active(),sessions=new Map(sets.map(s=>[s.session,s])),weeks=report.weekly.filter(w=>w.week<=$('#to').value&&new Date(w.week).getTime()+6*86400000>=new Date($('#from').value).getTime());
 // Reaggregate selected dates; duration counted once per session.
 weeks=weeks.map(w=>{let ss=sets.filter(s=>{let d=new Date(s.date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10)===w.week}),ssn=new Map(ss.map(s=>[s.session,s]));return {...w,sets:ss.length,volume:ss.reduce((a,s)=>a+s.volume,0),reps:ss.reduce((a,s)=>a+(s.reps||0),0),sessions:ssn.size,minutes:[...ssn.values()].reduce((a,s)=>a+s.minutes,0)}});
 let minutes=[...sessions.values()].reduce((a,s)=>a+s.minutes,0);$('#metrics').innerHTML=[['Workouts',sessions.size,'Sessions in selected range'],['Working sets',sets.length,'Warm-ups excluded'],['Logged volume',fmt(sets.reduce((a,s)=>a+s.volume,0)),'lb · external load × reps'],['Training time',fmt(minutes/60),'hours · logged duration']].map(([t,n,b])=>`<div class="metric"><small>${t}</small><strong>${n}</strong><span>${b}</span></div>`).join('');$('#weekly').innerHTML=chart(weeks,$('#metric').value);
 let counts={};sets.forEach(s=>counts[s.muscle]=(counts[s.muscle]||0)+1);let total=sets.length||1,cumulative=0;let stops=Object.entries(counts).map(([m,n],i)=>{let start=cumulative;cumulative+=n/total*100;return `${colors[i%colors.length]} ${start}% ${cumulative}%`});$('#distribution').innerHTML=`<div class="donut" style="background:conic-gradient(${stops.length?stops.join(','):'#233047 0% 100%'})"><div><strong>${sets.length}</strong><small>DIRECT SETS</small></div></div>`+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([m,n])=>`<div class="row"><span>${esc(m)}</span><b>${fmt(n/total*100)}% <small class="muted">· ${n} sets</small></b></div>`).join('');
 const oldDay=$('#day').value;$('#day').innerHTML='<option value="">Selected range</option>'+[...new Set(sets.map(s=>s.date))].sort().reverse().map(d=>`<option>${d}</option>`).join('');$('#day').value=oldDay;
 const oldWeek=$('#week').value;$('#week').innerHTML=weeks.slice().reverse().map(w=>`<option value="${w.week}">Week of ${w.week}</option>`).join('');if(weeks.some(w=>w.week===oldWeek))$('#week').value=oldWeek;
 renderAtlas();renderSets();renderExercise();renderMain();$('#insight-cards').innerHTML=report.insights.map(i=>`<article class="insight ${esc(i.tone)}"><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p></article>`).join('')+'<article class="insight"><h3>Test one change at a time</h3><p>Pick a goal, keep exercise technique consistent, and track reps at the same load. Add sleep, recovery and effort notes to understand possible contributors. Review trends across multiple sessions.</p></article>';}
function renderSets(){if(!$('#week').value){$('#set-counts').textContent='No weeks in selected range';return;}let w=$('#week').value,ss=active().filter(s=>s.date>=w&&s.date<=new Date(new Date(w).getTime()+6*86400000).toISOString().slice(0,10)),target=Number($('#target').value)||10;$('#set-counts').innerHTML=groups.map(m=>{let n=ss.filter(s=>s.muscle===m).length;return `<div class="row"><span>${m}</span><b>${n} <small class="muted">/ ${target} target</small></b></div><div class="bar"><span style="width:${Math.min(100,n/target*100)}%"></span></div>`}).join('');}
function renderAtlas(){const day=$('#day').value,ss=active().filter(s=>!day||s.date===day),count=m=>ss.filter(s=>s.muscle===m).length,max=Math.max(...groups.map(count),1);let svg='<svg class="atlas" viewBox="0 0 430 340" role="img" aria-label="Front and back muscle map">';
 for(let offset of [30,240]){svg+=`<g transform="translate(${offset},10)"><circle cx="75" cy="24" r="19" fill="#263244"/><path d="M48 48 Q75 40 102 48 L117 75 L107 142 L99 175 L107 246 L91 302 L74 302 L75 200 L63 302 L47 302 L39 246 L48 175 L39 142 L33 75 Z" fill="#192332" stroke="#46566c"/><path d="M36 65 L13 126 L9 183 L23 185 L39 128 L48 72 M104 65 L137 126 L141 183 L127 185 L111 128 L102 72" fill="#192332" stroke="#46566c"/>`;
 const back=offset===240;const shapes=back?[['Back','M49 62 L101 62 L95 136 L75 157 L55 136 Z'],['Glutes','M48 157 Q75 143 102 157 L98 187 L52 187 Z'],['Hamstrings','M50 192 L69 192 L65 249 L48 248 Z M80 192 L98 192 L102 248 L84 249 Z'],['Calves','M48 251 L65 251 L61 291 L49 291 Z M85 251 L102 251 L100 291 L88 291 Z'],['Triceps','M33 83 L43 91 L27 130 L17 127 Z M108 91 L117 83 L133 127 L123 130 Z']]:[['Chest','M48 62 Q60 51 73 66 L73 99 L47 92 Z M77 66 Q92 51 102 62 L103 92 L77 99 Z'],['Biceps','M31 88 L42 96 L29 125 L19 121 Z M108 96 L119 88 L131 121 L121 125 Z'],['Core','M58 106 L92 106 L94 146 L75 160 L56 146 Z'],['Quads','M49 179 L71 179 L66 243 L47 240 Z M79 179 L101 179 L104 240 L84 243 Z'],['Forearms','M17 133 L27 136 L20 173 L12 173 Z M123 136 L133 133 L139 173 L130 173 Z']];shapes.push(['Shoulders','M37 59 Q47 49 53 55 L47 82 L33 82 Z M98 55 Q105 49 114 59 L118 82 L104 82 Z']);
 for(let [m,path] of shapes)svg+=`<path tabindex="0" role="button" aria-label="${m}: ${count(m)} sets" class="muscle" data-muscle="${m}" d="${path}" fill="${count(m)?`rgba(36,156,255,${.25+.75*count(m)/max})`:'#243043'}"><title>${m}: ${count(m)} direct sets</title></path>`;svg+=`<text x="75" y="325" text-anchor="middle">${back?'BACK':'FRONT'}</text></g>`;}$('#atlas').innerHTML=svg+'</svg>';$('#muscle-detail').textContent=day?`Logged direct work on ${day}`:'Direct work across selected range';$('#atlas').querySelectorAll('[data-muscle]').forEach(el=>{let show=()=>{let m=el.dataset.muscle;$('#muscle-detail').textContent=`${m}: ${count(m)} direct sets · ${[...new Set(ss.filter(s=>s.muscle===m).map(s=>s.exercise))].join(', ')||'No direct work logged'}`};el.onclick=show;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();show()}}});}
function renderExercise(){let e=report.exercises.find(e=>e.name===$('#exercise').value);if(!e)return;let history=e.history.filter(r=>r.date>=$('#from').value&&r.date<=$('#to').value);$('#exercise-chart').innerHTML=chart(history,$('#exercise-metric').value,true);$('#exercise-detail').innerHTML=`<div class="row"><span>All-time top load</span><b>${fmt(e.best_weight)} lb</b></div><div class="row"><span>Estimated strength trend</span><b>${e.change===null?'Needs ≥6 eligible sessions':fmt(e.change)+'%'}</b></div><p class="muted">Epley estimate · eligible external-load sets of 1–12 reps. Compare the same exercise and equipment.</p>`;}
function renderMain(){const counts={};active().forEach(s=>{if(!counts[s.exercise])counts[s.exercise]=new Set();counts[s.exercise].add(s.session)});$('#main-exercises').innerHTML=Object.entries(counts).filter(([n])=>n.toLowerCase().includes($('#search').value.toLowerCase())).sort((a,b)=>b[1].size-a[1].size).map(([n,ss])=>`<div class="row"><span>${esc(n)}</span><span class="pill">${ss.size} sessions</span></div>`).join('');}
function readLocal(){try{weights=JSON.parse(localStorage.getItem('form-weight-v1')||'[]')}catch{weights=[];status('Weight storage could not be read. Restore a backup.')}}
function renderWeights(){weights.sort((a,b)=>a.date.localeCompare(b.date));$('#weight-chart').innerHTML=chart(weights,'weight_lb',true,true);let first=weights[0],last=weights.at(-1);$('#weight-summary').textContent=last?`Latest: ${fmt(last.weight_lb)} lb · Change since first log: ${fmt(last.weight_lb-first.weight_lb)} lb`:'Log your first weigh-in to begin.';$('#weight-list').innerHTML=weights.slice().reverse().map(w=>`<div class="row"><span>${esc(w.date)} · ${fmt(w.weight_lb)} lb<br><small class="muted">${esc(w.note)}</small></span><button data-date="${w.date}" aria-label="Delete weight for ${w.date}">×</button></div>`).join('');$('#weight-list').querySelectorAll('button').forEach(b=>b.onclick=async()=>{try{if(!localMode){let {error}=await client.from('workout_weights').delete().eq('user_id',user.id).eq('date',b.dataset.date);if(error)throw error;}weights=weights.filter(w=>w.date!==b.dataset.date);if(localMode)localStorage.setItem('form-weight-v1',JSON.stringify(weights));renderWeights();status('Weigh-in deleted')}catch(e){status(e.message)}})}
$('#weight-form').date.value=new Date().toLocaleDateString('en-CA');
$('#weight-form').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target),value=Number(f.get('weight'));if(!Number.isFinite(value)||value<=0)throw Error('Enter a valid weight');let w={date:f.get('date'),weight_lb:f.get('unit')==='kg'?value*2.2046226218:value,note:f.get('note')};if(!localMode){let {error}=await client.from('workout_weights').upsert({...w,user_id:user.id},{onConflict:'user_id,date'});if(error)throw error;}let next=weights.filter(x=>x.date!==w.date).concat(w);if(localMode)localStorage.setItem('form-weight-v1',JSON.stringify(next));weights=next;renderWeights();status(localMode?'Saved on this device. Export a backup for safekeeping.':'Saved securely to your account.')}catch(e){status(e.message)}};
$('#report-file').onchange=async e=>{try{let file=e.target.files[0];if(file.size>30000000)throw Error('Report exceeds 30MB');if(user)await client.auth.signOut();localMode=true;readLocal();load(JSON.parse(await file.text()));status('Private report loaded on this device.')}catch(e){status(e.message)}};
$('#weights-file').onchange=async e=>{try{if(!localMode)throw Error('Sign out and use local mode to restore a backup');let a=JSON.parse(await e.target.files[0].text());if(!Array.isArray(a)||a.some(w=>!/^\d{4}-\d{2}-\d{2}$/.test(w.date)||!Number.isFinite(w.weight_lb)||w.weight_lb<=0))throw Error('Invalid weight backup');weights=[...new Map(weights.concat(a).map(w=>[w.date,w])).values()];localStorage.setItem('form-weight-v1',JSON.stringify(weights));renderWeights();status('Backup restored')}catch(e){status(e.message)}};
$('#backup').onclick=()=>{let url=URL.createObjectURL(new Blob([JSON.stringify(weights,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='form-weight-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
for(let id of ['from','to','metric'])$('#'+id).onchange=()=>{if($('#from').value>$('#to').value){status('Start date must precede end date');return}render()};$('#reset').onclick=()=>{if(report){$('#from').value=report.range.start;$('#to').value=report.range.end;render()}};$('#day').onchange=renderAtlas;$('#week').onchange=renderSets;$('#target').onchange=renderSets;$('#exercise').onchange=renderExercise;$('#exercise-metric').onchange=renderExercise;$('#search').oninput=renderMain;
$('#demo').onclick=async()=>{try{if(user)await client.auth.signOut();localMode=true;readLocal();load(await (await fetch('demo.json')).json());status('DEMO DATA • fictional workouts. Weight entries remain local.')}catch(e){status(e.message)}};
async function cloudLoad(session){user=session?.user;$('#logout').hidden=!user;if(!user){report=null;$('#dashboard').hidden=true;weights=[];localMode=true;return}localMode=false;let [r,w]=await Promise.all([client.from('workout_reports').select('report').eq('user_id',user.id).maybeSingle(),client.from('workout_weights').select('date,weight_lb,note').eq('user_id',user.id).order('date')]);if(r.error||w.error)throw r.error||w.error;weights=w.data||[];if(r.data)load(r.data.report);else status('Signed in. Run Analyze workouts in GitHub Actions to publish your report.');}
$('#login').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target),{data,error}=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)throw error;e.target.reset();await cloudLoad(data.session)}catch(e){status(e.message)}};
$('#logout').onclick=async()=>{await client.auth.signOut();await cloudLoad(null);status('Signed out. Private data cleared from the page.')};
readLocal();
const config=window.WORKOUT_CONFIG;if(config.supabaseUrl&&config.publishableKey){try{let {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.102.0');client=createClient(config.supabaseUrl,config.publishableKey);$('#login').hidden=false;$('#connection').textContent='Sign in to access your private report and synced weigh-ins, or load a report locally.';let {data,error}=await client.auth.getSession();if(error)throw error;await cloudLoad(data.session);client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')cloudLoad(null)});}catch(e){status('Cloud connection unavailable: '+e.message)}}
